name: 'nb.gitversioning_validation'
description: 'Validate Nerdbank.GitVersioning against pull request version file'
inputs:
  github-token: # id of input
    description: 'Github token for authenticating client'
    require: false
    default: ${{ github.token }}
  version-json-path: # id of input
    description: 'Relative file path to version.json'
    require: false
    default: 'version.json'
  branch-name: # id of input
    description: 'Branch name of version.json to compare against'
    require: false
    default: ${{ github.base_ref }}
runs:
  using: 'node16'
  main: 'dist/index.js'